### PR TITLE
support syntest

### PR DESCRIPTION
**Pull request by Freed-Wu**
<http://www.sublimetext.com/docs/syntax.html#testing>

Screenshot

### CODE REVIEW

**Comment by Freed-Wu** [comment]
Where is conflict?

**Review by iamcco — APPROVED** [review]

**Comment by iamcco** [comment]
I resolve the conflict and still can not merge. https://github.com/iamcco/coc-diagnostic/pull/136/commits/5d530b408d422ce852de3861d4094882ef650bef

image

**Comment by Freed-Wu** [comment]
Screenshot_2022-11-20-00-16-27-87

**Comment by iamcco** [comment]
OK，skip rebase should be fine.

**Pull request merged**
