### PR TITLE
Add nix-linter

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by iamcco** [comment]
Thanks!

**Comment by expipiplus1** [comment]
Thanks!

On reflection, it might be best to use "info" or "warning" instead of "error" for these messages. Do you know if that's possible?

**Comment by iamcco** [comment]
Add `security` option for the linter, you can read the README of https://github.com/iamcco/diagnostic-languageserver#how-to-config-a-new-linter for more detail.

**Comment by expipiplus1** [comment]
The problem is that the program doesn't supply any field for security. Is it possible to put just a constant `"Warning"` in there?

**Comment by iamcco** [comment]
```
"securities": {
      "undefined": "warning"
}
```
if you do not add `security` then it's undefined, so you can add `securities` as above.

**Pull request merged**
