### PR TITLE
Make nix-linter messages warnings not errors

### PR DESCRIPTION
**Pull request by expipiplus1**
Also add nixfmt formatter

### CODE REVIEW

**Comment by expipiplus1** [comment]
As discussed here https://github.com/iamcco/coc-diagnostic/pull/56

**Comment by expipiplus1** [comment]
thanks! Will this see a release on npm soon?

**Comment by iamcco** [comment]
I have already publish new package to npm.

**Comment by expipiplus1** [comment]
wow, amazing!

**Pull request merged**
