### PR TITLE
Prefer space indentation on shfmt

### PR DESCRIPTION
**Pull request by mosheavni**

### CODE REVIEW

**Comment by lithammer** [comment]
This seems like a very bad default and should be reverted imo. If your preference is 2-space indentation instead of the default (tabs), you can configure it via an [EditorConfig](https://editorconfig.org). In fact, adding this flags causes shfmt to _not_ use any EditorConfig making this unusable on any project that uses one:

> If any EditorConfig files are found, they will be used to apply formatting options. If any parser or printer flags are given to the tool, no EditorConfig files will be used. A default like -i=0 can be used for this purpose.

https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd

**Comment by mosheavni** [comment]
> This seems like a very bad default and should be reverted imo. If your preference is 2-space indentation instead of the default (tabs), you can configure it via an [EditorConfig](https://editorconfig.org). Or create an `args` override in your `coc-settings.json`.
> 
> In fact, adding this flag causes shfmt to ignore EditorConfig making this unusable on any project that uses one:
> 
> > If any EditorConfig files are found, they will be used to apply formatting options. If any parser or printer flags are given to the tool, no EditorConfig files will be used. A default like -i=0 can be used for this purpose.
> 
> There's even an example at the bottom of the manpage with an example on how to configure it.
> 
> https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd

I have a valid working editorconfig and shfmt didn't consider it, it just added a tab all of a sudden (probably upgraded shfmt where this was added)

**Comment by lithammer** [comment]
Maybe shfmt didn't find your `.editorconfig` for some reason? Works fine for me using shfmt v3.4.2.

If you revert this change, are you still having issues with shfmt not using your editorconfig?

**Comment by lithammer** [comment]
> it just added a tab all of a sudden

I had a similar experience, but the other way around. And didn't understand why shfmt on the command-line did the right thing, but not Vim.

**Comment by mosheavni** [comment]
> Maybe shfmt didn't find your `.editorconfig` for some reason? EditorConfig integration works fine for me using shfmt v3.4.2.
> 
> If you revert this change, are you still having issues with shfmt not using your EditorConfig?

Tested now, looks like it does consider it this time.

**Pull request merged**
